[package]
name = "minlz-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.minlz]
path = ".."

[[bin]]
name = "encode_decode_roundtrip"
path = "fuzz_targets/encode_decode_roundtrip.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode_arbitrary"
path = "fuzz_targets/decode_arbitrary.rs"
test = false
doc = false
bench = false

[[bin]]
name = "block_level_encoders"
path = "fuzz_targets/block_level_encoders.rs"
test = false
doc = false
bench = false
